# Generated by Django 5.2.17 on 2026-08-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('school_admin', 'School Admin'), ('teacher', 'Teacher'), ('student', 'Student')], max_length=20, null=True),
        ),
    ]
