# Generated by Django 6.0.7 on 2026-07-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_admission_no_alter_student_class_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profiles_pics/'),
        ),
    ]
