# Generated by Django 6.0.7 on 2026-07-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_student_class_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, help_text='Enter the address of the student', max_length=50, null=True),
        ),
    ]
