# Generated by Django 5.2.17 on 2026-08-11 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("section", "0001_initial"),
        ("subject", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Subjects",
            new_name="Subject",
        ),
    ]
