# Generated by Django 6.0.7 on 2026-08-01 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_class_class_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='class_teacher',
        ),
    ]
