# Generated by Django 5.2.17 on 2026-08-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school_name", models.TextField(max_length=50)),
                (
                    "school_board",
                    models.CharField(
                        choices=[
                            ("CBSE", "CBSE"),
                            ("ICSE", "ICSE"),
                            ("State Board", "State Board"),
                            ("IB", "IB"),
                            ("OTHER", "OTHER"),
                        ],
                        default="CBSE",
                        max_length=20,
                    ),
                ),
                (
                    "conatact_number",
                    models.CharField(max_length=15, null=True, unique=True),
                ),
                ("email", models.EmailField(max_length=50, null=True, unique=True)),
                ("address", models.CharField(max_length=100)),
                ("joined_date", models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
