# Generated by Django 6.0.7 on 2026-07-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='conatact_number',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='school',
            name='email',
            field=models.EmailField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='school',
            name='joined_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='school_board',
            field=models.CharField(choices=[('CBSE', 'CBSE'), ('ICSE', 'ICSE'), ('State Board', 'State Board'), ('IB', 'IB'), ('OTHER', 'OTHER')], default='CBSE', max_length=20),
        ),
    ]
