# Generated by Django 6.0.7 on 2026-08-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_remove_class_class_teacher'),
        ('teacher', '0002_teacher_first_name_teacher_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='class_teacher_of',
        ),
        migrations.AddField(
            model_name='teacher',
            name='class_teacher_of',
            field=models.ManyToManyField(to='classes.class'),
        ),
    ]
