# Generated by Django 6.0.7 on 2026-08-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_remove_class_class_teacher'),
        ('teacher', '0003_remove_teacher_class_teacher_of_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='class_teacher_of',
            field=models.ManyToManyField(blank=True, related_name='class_teacher_of', to='classes.class'),
        ),
    ]
