# Generated by Django 5.2.17 on 2026-08-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
